%% DISPLAY
c1=meD.L(3)/2-meD.h(1)/2;
c2=meD.L(3)/2+meD.h(1)/2;
[np] = find(x(:,2)>c1 & x(:,2)<c2);
np = 1:mpD.n;

fig3=figure(3);
set(fig3,'Units','pixels','Position',[687 494 2*459 327]);
subplot(2,2,1)
    scatter3(x(np,1),x(np,2),x(np,3),4.0,du(np),'filled');
    axis equal;
    zlabel('$z$ [m]');
    zticks([0 5 10]);
    zlim([0 lz]);
    set(gca,'FontSize',12,'TickLabelInterpreter','latex');
    cb=colormap(jet);
        cb=colorbar('FontSize',10,'TickLabelInterpreter','latex','Fontsize',10,'Location','south');
        cb.Position         =[0.5 0.2 0.1 0.05];
        cb.Label.String     ='$u_p$ [m]';
        cb.Label.Units      ='normalized';
        cb.Label.Position   =[0.5 2.2];
        cb.Label.FontSize   =10;
        cb.Label.Interpreter='Latex';
    box on;
    view(0,0);
    title('a) vertical profile','FontSize',12);
subplot(2,2,3);
    scatter3(x(np,1),x(np,2),x(np,3),4.0,du(np),'filled');
    axis equal;
    xlabel('$x$ [m]');
    ylabel('$y$ [m]');
    yticks([0 5 10]);
    set(gca,'FontSize',12,'TickLabelInterpreter','latex');
    box on;
    view(0,90);
    title('b) aerial view','FontSize',12);
subplot(2,2,[2,4]);
    scatter3(x(np,1),x(np,2),x(np,3),4.0,du(np),'filled');
    axis equal;
    xlabel('$x$ [m]');
    ylabel('$y$ [m]');
    zlabel('$z$ [m]');
    yticks([0 5 10]);
    zticks([0 5 10]);
    zlim([0 lz]);
    set(gca,'FontSize',12,'TickLabelInterpreter','latex');
    box on;
        ax = gca;
        ax.BoxStyle = 'full';
    view(47,13);
    title('c) perspective','FontSize',12);
set(gcf,'color','white');
name = strcat(['Exp2b_u_',num2str(sim),'']);
print(fig3,name,'-dpng','-r600');
print(fig3,name,'-depsc','-r600');

%% DISPLAY
c1=meD.L(3)/2-meD.h(1)/2;
c2=meD.L(3)/2+meD.h(1)/2;
[np] = find(x(:,2)>c1 & x(:,2)<c2);
np = 1:mpD.n;

fig4=figure(4);
set(fig4,'Units','pixels','Position',[687 494 2*459 327]);
subplot(2,2,1)
    scatter3(x(np,1),x(np,2),x(np,3),4.0,epII(np),'filled');
    axis equal;
    zlabel('$z$ [m]');
    zticks([0 5 10]);
    zlim([0 lz]);
    set(gca,'FontSize',12,'TickLabelInterpreter','latex');
    cb=colormap(jet);
        cb=colorbar('FontSize',10,'TickLabelInterpreter','latex','Fontsize',10,'Location','south');
        cb.Position         =[0.5 0.2 0.1 0.05];
        cb.Label.String     ='$\epsilon_{\mathrm{eqv}}^p$ [-]';
        cb.Label.Units      ='normalized';
        cb.Label.Position   =[0.5 2.2];
        cb.Label.FontSize   =10;
        cb.Label.Interpreter='Latex';
    box on;
    view(0,0);
    title('a) vertical profile','FontSize',12);
subplot(2,2,3);
    scatter3(x(np,1),x(np,2),x(np,3),4.0,epII(np),'filled');
    axis equal;
    xlabel('$x$ [m]');
    ylabel('$y$ [m]');
    yticks([0 5 10]);
    set(gca,'FontSize',12,'TickLabelInterpreter','latex');
    box on;
    view(0,90);
    title('b) aerial view','FontSize',12);
subplot(2,2,[2,4]);
    a = ones(size(epII)); a(epII<1) = 1;
    s = scatter3(x(np,1),x(np,2),x(np,3),4.0,epII(np),'filled');
        s.MarkerFaceAlpha = 'flat';
        s.AlphaData       = a;
    axis equal;
    xlabel('$x$ [m]');
    ylabel('$y$ [m]');
    zlabel('$z$ [m]');
    yticks([0 5 10]);
    zticks([0 5 10]);
    zlim([0 lz]);
    set(gca,'FontSize',12,'TickLabelInterpreter','latex');
    box on;
        ax = gca;
        ax.BoxStyle = 'full';
    view(47,13);
    title('c) perspective','FontSize',12);
set(gcf,'color','white');
name = strcat(['Exp2b_epsEqv_',num2str(sim),'']);
print(fig4,name,'-dpng','-r600');
print(fig4,name,'-deps','-r600');